name: Generate and Increment Tag
description: Generate and increment the latest git tag.

outputs:
  tag:
    description: "Release tag"
    value: ${{ steps.new-release-tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Generate and Increment Tag
      id: new-release-tag
      shell: bash
      run: |
        git fetch --tags

        # Check if any tags exist
        if [ $(git tag | wc -l) -eq 0 ]; then
          echo "No tags found in the repository. Starting from v0.1.0."
          new_tag="v0.1.0"
        else
          # Fetch the latest tag
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag found: $latest_tag"

          # Strip the 'v' prefix if it exists
          clean_tag=${latest_tag#v}

          # Split the tag into major, minor, patch
          IFS='.' read -r major minor patch <<< "$clean_tag"

          # Increment the patch version
          new_patch=$((patch + 1))

          # Construct the new tag
          new_tag="v${major}.${minor}.${new_patch}"
        fi

        # Output the new tag
        echo "New tag is $new_tag"
        echo "tag=$new_tag" >> $GITHUB_OUTPUT
